
//----------------------------------------------------
// The following code was generated by CUP v0.11b 
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQUALS = 36;
  public static final int LSQUARE = 42;
  public static final int MINUS = 30;
  public static final int DISPLAY = 24;
  public static final int READOP = 8;
  public static final int GREATER = 39;
  public static final int LPAREN = 19;
  public static final int INTEGER = 3;
  public static final int PLUSPLUS = 27;
  public static final int DIVIDE = 32;
  public static final int LESS = 38;
  public static final int STRUCT = 7;
  public static final int OR = 35;
  public static final int BOOLEAN = 2;
  public static final int COMMA = 22;
  public static final int RPAREN = 20;
  public static final int NOT = 33;
  public static final int COLON = 21;
  public static final int AND = 34;
  public static final int PLUS = 29;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 28;
  public static final int RETURN = 13;
  public static final int TRUE = 5;
  public static final int RSQUARE = 1;
  public static final int LCURLY = 17;
  public static final int VOID = 4;
  public static final int NOTEQ = 37;
  public static final int WHILE = 12;
  public static final int LESSEQ = 40;
  public static final int ASSIGN = 26;
  public static final int IF = 10;
  public static final int DOT = 23;
  public static final int ID = 14;
  public static final int RCURLY = 18;
  public static final int INTLIT = 15;
  public static final int TIMES = 31;
  public static final int ELSE = 11;
  public static final int INPUT = 25;
  public static final int GREATEREQ = 41;
  public static final int STRINGLIT = 16;
  public static final int FALSE = 6;
  public static final int WRITEOP = 9;
}
